### ISSUE TITLE
bug: cannot update global state schema and initial state more than once

### ISSUE THREAD

**Issue by ryanwolhuter** [powerhouse-inc/document-model-libs#32]
The global state schema and initial state cannot be updated after they have been added the first time. We should be able to trigger these operations any number of times.

**Comment by ryanwolhuter** [comment]
@gpuente I was going to take this one, but since you're working on the new undo/redo now I think it might be redundant. Let me know if you think the problems are unrelated and I'll grab it, otherwise we can close this one

**Comment by gpuente** [comment]
@ryanwolhuter I think this issue can be solved with the new undo/redo, but I'm not 100% sure. let's keep it open for now, If after the new undo/redo this issue is still there, we can address it, otherwise we can close it.

**Comment by ryanwolhuter** [comment]
@gpuente @acaldas this is unfortunately still happening with the newly updated packages — there's a problem with how states are updated after the initial creation of the document model. 

This also happens when trying to update the schemas for operations.
